//! Parity test for a trained CodeDeltaTok checkpoint.
//!
//! Complements `cdt_parity.rs` (which uses a random-init model): loads the
//! converted `cdt_paper.safetensors` built with `convert-cdt` and asserts
//! that Synapse's forward pass reproduces the PyTorch model's delta + recon
//! on the 8 reference (h_b, h_a) pairs from the fixture.
//!
//! Skips when the fixture isn't present (we only ship the random-init one
//! in the repo; the trained one is locally generated by
//! `scripts/export_unixcoder_reference.py convert-cdt`).

use std::path::PathBuf;

use synapse_inference::models::text_encoder::{CodeDeltaTokConfig, CodeDeltaTokHead};
use synapse_inference::weight_loading::{load_safetensors, WeightMapper};

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .to_path_buf()
}

fn cosine(a: &[f32], b: &[f32]) -> f32 {
    let mut dot = 0.0f32;
    let mut na = 0.0f32;
    let mut nb = 0.0f32;
    for (x, y) in a.iter().zip(b) {
        dot += x * y;
        na += x * x;
        nb += y * y;
    }
    dot / (na.sqrt() * nb.sqrt() + 1e-30)
}

fn max_abs(a: &[f32], b: &[f32]) -> f32 {
    a.iter().zip(b).map(|(x, y)| (x - y).abs()).fold(0f32, f32::max)
}

#[test]
fn cdt_trained_head_matches_pytorch() {
    let fixture_path = repo_root()
        .join("crates/synapse-inference/tests/fixtures/cdt_paper.safetensors");
    if !fixture_path.exists() {
        eprintln!(
            "SKIP: {} missing. Run \
             `python scripts/export_unixcoder_reference.py convert-cdt \
             --ckpt <code_deltatok_final.pt> \
             --ref crates/synapse-inference/tests/fixtures/unixcoder_ref.safetensors \
             --out crates/synapse-inference/tests/fixtures/cdt_paper.safetensors`.",
            fixture_path.display(),
        );
        return;
    }
    let fx = load_safetensors(&fixture_path).expect("load cdt fixture");

    let mut head = CodeDeltaTokHead::from_config(CodeDeltaTokConfig::paper_default());
    let result = head
        .load_weights(fx.clone(), &WeightMapper::code_deltatok())
        .expect("load_weights");
    assert!(result.missing.is_empty(),
            "Missing CDT targets: {:?}", result.missing);

    let d = head.config.feature_dim;
    let k = head.config.num_delta_tokens;

    let h_b = fx.get("parity.h_b").unwrap();
    let h_a = fx.get("parity.h_a").unwrap();
    let delta_ref = fx.get("parity.delta").unwrap();
    let recon_ref = fx.get("parity.recon").unwrap();
    let batch = h_b.shape[0];
    assert_eq!(h_b.shape, vec![batch, d]);
    assert_eq!(delta_ref.shape, vec![batch, k, d]);
    assert_eq!(recon_ref.shape, vec![batch, d]);

    let mut worst_delta_cos = 1.0f32;
    let mut worst_recon_cos = 1.0f32;
    let mut worst_delta_abs = 0.0f32;
    let mut worst_recon_abs = 0.0f32;

    for b in 0..batch {
        let hb = &h_b.data[b * d..(b + 1) * d];
        let ha = &h_a.data[b * d..(b + 1) * d];

        let delta = head.encode(hb, ha);
        let recon = head.decode(&delta, hb);

        let delta_t = &delta_ref.data[b * k * d..(b + 1) * k * d];
        let recon_t = &recon_ref.data[b * d..(b + 1) * d];

        worst_delta_cos = worst_delta_cos.min(cosine(&delta, delta_t));
        worst_recon_cos = worst_recon_cos.min(cosine(&recon, recon_t));
        worst_delta_abs = worst_delta_abs.max(max_abs(&delta, delta_t));
        worst_recon_abs = worst_recon_abs.max(max_abs(&recon, recon_t));
    }

    println!(
        "CDT trained parity (batch={batch}): delta cos = {worst_delta_cos:.6}, \
         recon cos = {worst_recon_cos:.6}, delta max_abs = {worst_delta_abs:.5}, \
         recon max_abs = {worst_recon_abs:.5}",
    );

    assert!(worst_delta_cos >= 0.9999,
            "delta cosine {worst_delta_cos} < 0.9999");
    assert!(worst_recon_cos >= 0.9999,
            "recon cosine {worst_recon_cos} < 0.9999");
    assert!(worst_delta_abs < 1e-3,
            "delta max_abs {worst_delta_abs} >= 1e-3");
    assert!(worst_recon_abs < 1e-3,
            "recon max_abs {worst_recon_abs} >= 1e-3");
}
